spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/glailton/microservices-config-server.git
          username: glailton
          password: Gl@ilton26
          clone-on-start: true
server:
  port: 8888

